spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://api.fantuan.io:9999
    auth-service:
      path: /user/**
      url: http://auth.fantuan.io:8181/uaa/user
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.fantuan.io:8761/eureka/
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://auth.fantuan.io:8181/uaa/user
    client:
      accessTokenUri: http://auth.fantuan.io:8181/uaa/oauth/token
      userAuthorizationUri: http://auth.fantuan.io:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**

---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/